language: node_js
node_js:
  - "node"
  - "7"
  - "6"
install:
  - npm install
  - npm install -g codecov
  - npm run flow-typed-install
script:
  - npm test -- --coverage && codecov
  - npm run lint
  - npm run flow-check